// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Goldilocks Carnival",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Goldilocks Carnival",
            targets: ["AppModule"],
            bundleIdentifier: "com.dassy.carnival",
            teamIdentifier: "VGKCD7Q8NW",
            displayVersion: "1.0",
            bundleVersion: "6",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/onevcat/Kingfisher.git", "7.2.4"..<"8.0.0"),
        .package(url: "https://github.com/paololeonardi/WaterfallGrid.git", "1.0.1"..<"2.0.0"),
        .package(url: "https://github.com/CSolanaM/SkeletonUI.git", "1.0.9"..<"2.0.0"),
        .package(url: "https://github.com/AlexRoar/SwiftYFinance", "1.5.0"..<"2.0.0"),
        .package(url: "https://github.com/airbnb/lottie-ios.git", "4.0.1"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "WaterfallGrid", package: "WaterfallGrid"),
                .product(name: "SkeletonUI", package: "SkeletonUI"),
                .product(name: "SwiftYFinance", package: "SwiftYFinance"),
                .product(name: "Lottie", package: "lottie-ios")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
